version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Deploying lf1.zip to LF1-pipeline"
      - aws lambda update-function-code --function-name LF1-pipeline --zip-file fileb://lf1.zip

      - echo "Deploying lf2.zip to LF2-pipeline"
      - aws lambda update-function-code --function-name LF2-pipeline --zip-file fileb://lf2.zip

artifacts:
  files:
    - lf1.zip
    - lf2.zip
